---

- name: ensure mail user is present
  user:
    name: vmail
    home: "{{ dovecot_vmail_path }}"
    shell: /bin/false
    state: present
    uid: "{{ dovecot_mail_uid }}"

- name: ensure mail home is present
  file:
    path: "{{ dovecot_vmail_path }}"
    state: directory
    owner: vmail
    group: vmail
    mode: "u+rw,g+rw,o-rwx"

- name: ensure dovecot is installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - dovecot-core
    - dovecot-common
    - dovecot-imapd
    - dovecot-pop3d

- name: ensure dovecot is in group of user-management
  user:
    name: dovecot
    append: true
    groups: "{{ dovecot_usrmgmt_user }}"

- name: set instance_name
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    line: "instance_name = {{ ansible_fqdn }}"
    regexp: "instance_name ="
  notify: restart dovecot

- name: set login greeting
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    line: "login_greeting = {{ ansible_fqdn }} ready."
    regexp: "login_greeting ="
  notify: restart dovecot

- name: copy checkpassword auth config
  template:
    src: auth-checkpassword.conf.ext.j2
    dest: /etc/dovecot/conf.d/auth-checkpassword.conf.ext
    owner: root
    group: root
    mode: 0644

- name: configure dovecot
  template:
    src: "{{ item }}.j2"
    dest: /etc/dovecot/conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
  notify: restart dovecot

# see https://github.com/systemli/user-management/issues/33#issuecomment-435371352
- name: copy fallback sql config for LDA
  template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext
    owner: root
    group: root
    mode: 0600
  when: dovecot_sql_url is defined
  notify: restart dovecot

- import_tasks: munin.yml
  when: dovecot_munin
  tags: munin
