---

- name: ensure mail user is present
  user:
    name: vmail
    home: "{{ dovecot_vmail_path }}"
    shell: /bin/false
    state: present
    uid: "{{ dovecot_mail_uid }}"
  when: not dovecot_backup_follower

- name: ensure mail user is present
  user:
    name: vmail
    home: "{{ dovecot_vmail_path }}"
    shell: /bin/bash
    state: present
    uid: "{{ dovecot_mail_uid }}"
  when: dovecot_backup_follower

- name: ensure mail home is present
  file:
    path: "{{ dovecot_vmail_path }}"
    state: directory
    owner: vmail
    group: vmail
    mode: "u+rw,g+rw,o-rwx"

- name: ensure dovecot is installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - dovecot-core
    - dovecot-common
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-lmtpd
    - dovecot-sieve
    - dovecot-managesieved

- name: ensure dovecot is in group of user-management
  user:
    name: dovecot
    append: true
    groups: "{{ dovecot_usrmgmt_user }}"

- name: set instance_name
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    line: "instance_name = {{ ansible_fqdn }}"
    regexp: "instance_name ="
  notify: restart dovecot

- name: set login greeting
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    line: "login_greeting = {{ ansible_fqdn }} ready."
    regexp: "login_greeting ="
  notify: restart dovecot

- name: copy checkpassword auth config
  template:
    src: auth-checkpassword.conf.ext.j2
    dest: /etc/dovecot/conf.d/auth-checkpassword.conf.ext
    owner: root
    group: root
    mode: 0644
  notify: restart dovecot

- name: create self-signed ssl cert
  block:
    - template:
        src: dovecot-openssl.cnf.j2
        dest: /etc/dovecot/dovecot-openssl.cnf
        owner: root
        group: root
        mode: 0644

    - command: /usr/share/dovecot/mkcert.sh
      args:
        creates: /etc/dovecot/dovecot.pem
        chdir: /etc/dovecot
  when: not dovecot_ssl_cert is defined

- name: configure dovecot
  template:
    src: "{{ item }}.j2"
    dest: /etc/dovecot/conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
    - 10-ssl.conf
  notify: restart dovecot

- name: configure mail_crypt
  copy:
    src: 90-mail-crypt.conf
    dest: /etc/dovecot/conf.d/
    owner: root
    group: root
    mode: 0644
  notify: restart dovecot
  when: '"mail_crypt" in dovecot_mail_plugins'

- import_tasks: munin.yml
  when: dovecot_munin
  tags: munin

- import_tasks: dovecot_backup_lead.yml
  when: dovecot_backup_lead
  tags:
    - dovecot_backup
    - dovecot_backup_lead

- import_tasks: dovecot_backup_follower.yml
  when: dovecot_backup_follower
  tags:
    - dovecot_backup
    - dovecot_backup_follower
