---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: dovecot-bookworm64
    box: debian/bookworm64

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible
  ansible_args:
    - --diff
  become: true
