---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: dovecot-bullseye64
    box: debian/bullseye64

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible
  become: true
